# Generated by Django 5.1.7 on 2025-03-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fitness_goal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
